version: '3.6'
services:
  postgres:
    image: postgres:latest
    restart: always
    user: root
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: summarization
    volumes:
      - /private/var/lib/postgres/data
    ports:
      - 5432:5432