"""'document'

Revision ID: 69ebced42193
Revises: 
Create Date: 2022-03-28 19:02:56.552739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ebced42193'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('document_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('document_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    # ### end Alembic commands ###
